version: '3'

services:
  db:
    image: postgres:12.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    tty: true
    stdin_open: true

  cli:
    build:
      context: .
      dockerfile: docker/cli/Dockerfile
    user: "1000:1000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db/transaction_dev
    volumes:
      - .:/app
      - /app/target/
    depends_on:
      - db
    tty: true
    stdin_open: true
